need to check the length of data list. even though the result is COMM_SUCCESS, sometimes data doesn't have enough value
Traceback (most recent call last):
  File "/home/chans/catkin_ws/src/choom_ax/scripts/master_node.py", line 204, in <module>
    read_and_publish()
  File "/home/chans/catkin_ws/src/choom_ax/scripts/master_node.py", line 117, in read_and_publish
    motor_msg.ID12 = read_position(12)
  File "/home/chans/catkin_ws/src/choom_ax/scripts/master_node.py", line 142, in read_position
    dxl_present_position, dxl_comm_result, dxl_error = packetHandler.read2ByteTxRx(portHandler, id, AX12_TABLE.ADDR_PRESENT_POSITION)
  File "/home/chans/catkin_ws/src/DynamixelSDK/ros/src/dynamixel_sdk/protocol1_packet_handler.py", line 376, in read2ByteTxRx
    data_read = DXL_MAKEWORD(data[0], data[1]) if (result == COMM_SUCCESS) else 0
IndexError: list index out of range
chans@chans-desktop:~/catkin_ws$